### PR TITLE
Solved #14 adding automatic JSON parser via options

### PR DESCRIPTION
**Pull request by haxpor**
Set options.parseJson to true (default to false) to automatically parse
JSON when data returned from request.

Error handling from trying to parse JSON is added as well, and return
via normal callback (cb).

### CODE REVIEW

**Comment by maradotwebp** [comment]
Please add unit tests and documentation according to the new [guidelines](https://github.com/froehlichA/apidown/blob/master/CONTRIBUTING.md). Otherwise, great work!

**Comment by haxpor** [comment]
I have added test case, and document along with refactor testing code extensively. Should be fine now. Please check additional commit just pushed :)

**Comment by maradotwebp** [comment]
@haxpor Please consider improving your coverage. I can't seem to be able to view the report right now.

**Comment by maradotwebp** [comment]
Thanks for your contribution @haxpor ! It means very much to me.

**Pull request merged**
